// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/cordova-plugin-app-version/cordova-plugin-app-version.d.ts
interface Cordova {
	getAppVersion: {
		getAppName: () => Q.IPromise<string> | JQueryPromise<string>;
		getPackageName: () => Q.IPromise<string> | JQueryPromise<string>;
		getVersionCode: () => Q.IPromise<string> | JQueryPromise<string>;
		getVersionNumber: () => Q.IPromise<string> | JQueryPromise<string>;
	};
}